from langchain_community.chat_models import ChatOllama
from langchain_core.messages import SystemMessage, HumanMessage
from state.travel_state import TravelState
from utils.logger import setup_logger
from tools.activity_tool import get_local_activities, generate_daily_schedule

logger = setup_logger("ItineraryAgent")

# Initialize the local LLM
llm = ChatOllama(model="llama3", temperature=0.7)

SYSTEM_PROMPT = """
You are the expert Itinerary Agent for TripGenie.
I will provide you with a drafted markdown schedule containing activities and the hotel.
Your job is to rewrite the itinerary to make it sound exciting, engaging, and personalized for the traveler.
You MUST output ONLY the finalized markdown itinerary. Do NOT output any conversational text or JSON. 
Just the beautifully formatted markdown content.
"""

def itinerary_node(state: TravelState) -> TravelState:
    """
    Itinerary Agent: Recommends activities and formats the final schedule using Llama3.
    """
    logger.info("Itinerary Agent Started")
    
    destination = state.get("destination", "Unknown")
    days = state.get("days", 1)
    hotels = state.get("hotels", [])
    
    hotel_name = hotels[0]["name"] if hotels else "TBD"
    
    # 1. Tool Call: Fetch activities deterministically
    local_activities = get_local_activities(destination)
    state["activities"] = local_activities
    
    # 2. Tool Call: Generate skeleton schedule deterministically
    draft_schedule = generate_daily_schedule(days, destination, hotel_name, local_activities)
    logger.info("Generated Skeleton Draft Schedule via Tool")
    
    # 3. LLM Call: Polish the schedule into a final readable itinerary
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=f"Please rewrite this draft itinerary to be exciting:\n\n{draft_schedule}")
    ]
    
    try:
        logger.info("Calling Llama3 LLM to finalize itinerary text...")
        response = llm.invoke(messages)
        final_itinerary = response.content.strip()
        logger.info("LLM Successfully generated final itinerary")
        
        # Inject the budget tip generated by Student 2
        if state.get("budget") and state["budget"].get("tip"):
            final_itinerary += f"\n\n---\n💡 **TripGenie Financial Tip**: {state['budget']['tip']}"
            
        state["itinerary"] = final_itinerary
        
    except Exception as e:
        logger.warning(f"LLM failed to rewrite itinerary. Using draft fallback. Error: {e}")
        # Fallback to the tool's raw draft
        
        if state.get("budget") and state["budget"].get("tip"):
            draft_schedule += f"\n\n---\n💡 **TripGenie Financial Tip**: {state['budget']['tip']}"
            
        state["itinerary"] = draft_schedule
        
    logger.info("Itinerary Agent Finished")
    return state
